version: '3'
services:
    database:
        image: postgres:10-alpine
        restart: always
        environment:
            POSTGRES_DATABASE_LOCAL: contact_db
            POSTGRES_DB: contact_db
            POSTGRES_HOST_LOCAL: localhost
            POSTGRES_PASSWORD_LOCAL: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_PORT_LOCAL: 5432
            POSTGRES_USER_LOCAL: postgres
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - network
    migrate:
        image: migrate/migrate
        networks:
            - network
        volumes:
            - ./database:/database
        command: ["-path", "/database", "-database",  "postgres://postgres:postgres@database:5432/contact_db?sslmode=disable", "up"]
        depends_on:
            database:
                condition: service_healthy
networks:
    network:
        driver: bridge
